---
# See https://github.com/jvautier/project-cli
fullname: jvautier/ansible-role-azure-cli
description: Install azure-cli through ansible
tags:
  - ansible
  - ansible-role
  - azure-cli
github:
  has_issues: true
  has_projects: false
  has_wiki: false
