---
- name: install key (apt)
  become: true
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: install azure-cli repo (apt)
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release|lower }} main"
    filename: azure-cli
    state: present

- name: install azure-cli
  become: true
  apt:
    name: azure-cli
    state: present
